export const treeData = [
  // CENTER
  {
    id: "start",
    x: 1500,
    y: 1500,
    type: "start",
    icon: "🎯",
    name: "QA Tester",
    desc: "The foundation of quality.",
  },
  // NORTH
  {
    id: "gm_mechanics",
    x: 1500,
    y: 1400,
    icon: "⚔️",
    name: "Game Mechanics",
    desc: "Verifying damage, jumping, and core loops.",
  },
  {
    id: "gm_collision",
    x: 1500,
    y: 1300,
    icon: "🧱",
    name: "Collision & Walls",
    desc: "Checking for invisible walls or falling through floors.",
  },
  {
    id: "gm_ui",
    x: 1420,
    y: 1300,
    icon: "🖱️",
    name: "UI/HUD Testing",
    desc: "Are menus readable? Do buttons actually work?",
  },
  {
    id: "gm_save",
    x: 1580,
    y: 1300,
    icon: "💾",
    name: "Save/Load",
    desc: "Does the game remember my progress after quitting?",
  },
  {
    id: "gm_progression",
    x: 1500,
    y: 1200,
    icon: "📈",
    name: "Progression",
    desc: "Unlocking levels and earning XP correctly.",
  },
  {
    id: "gm_master",
    x: 1500,
    y: 1100,
    type: "keystone",
    icon: "🎮",
    name: "Player Experience",
    desc: "KEYSTONE: You verify the 'Fun' factor.",
  },
  {
    id: "gm_audio",
    x: 1360,
    y: 1350,
    icon: "🔊",
    name: "Audio & SFX",
    desc: "Is the music looping? Are footsteps synced?",
  },
  {
    id: "gm_loc",
    x: 1340,
    y: 1250,
    icon: "🏳️",
    name: "Localization (L10n)",
    desc: "Text overflow and missing translations.",
  },
  {
    id: "gm_physics",
    x: 1640,
    y: 1350,
    icon: "🍎",
    name: "Physics",
    desc: "Ragdolls acting crazy or objects floating.",
  },
  {
    id: "gm_tuto",
    x: 1660,
    y: 1250,
    icon: "👶",
    name: "Tutorials",
    desc: "FTUE: Does the game actually teach the player?",
  },
  {
    id: "gm_balance",
    x: 1500,
    y: 1020,
    icon: "⚖️",
    name: "Game Balance",
    desc: "Is the boss too hard? Is the weapon too weak?",
  },
  // SOUTH
  {
    id: "bug_write",
    x: 1500,
    y: 1600,
    icon: "📝",
    name: "Clear Titles",
    desc: "Writing [Tag] Titles that devs understand instantly.",
  },
  {
    id: "bug_steps",
    x: 1500,
    y: 1700,
    icon: "👣",
    name: "Reproduction Steps",
    desc: "Exact 1-2-3 steps to make the bug happen again.",
  },
  {
    id: "bug_media",
    x: 1420,
    y: 1800,
    icon: "📸",
    name: "Evidence",
    desc: "Taking clear screenshots and trimming videos.",
  },
  {
    id: "bug_sev",
    x: 1580,
    y: 1800,
    icon: "⚠️",
    name: "Severity & Priority",
    desc: "Knowing the difference between a Crash and a Typo.",
  },
  {
    id: "bug_master",
    x: 1500,
    y: 1900,
    type: "keystone",
    icon: "📫",
    name: "Perfect Ticket",
    desc: "KEYSTONE: Your tickets never get sent back as 'Cannot Reproduce'.",
  },
  {
    id: "bug_search",
    x: 1400,
    y: 1620,
    icon: "🔍",
    name: "Search Dupes",
    desc: "Checking if someone else already reported it.",
  },
  {
    id: "bug_expected",
    x: 1600,
    y: 1620,
    icon: "🆚",
    name: "Expected Result",
    desc: "Clearly stating what *should* have happened.",
  },
  {
    id: "bug_version",
    x: 1380,
    y: 1720,
    icon: "📌",
    name: "Version Control",
    desc: "Reporting the correct Build Number.",
  },
  {
    id: "bug_corner",
    x: 1620,
    y: 1720,
    icon: "📐",
    name: "Corner Cases",
    desc: "Bugs that only happen in very weird situations.",
  },
  {
    id: "bug_reopen",
    x: 1500,
    y: 1980,
    icon: "🔁",
    name: "Verification",
    desc: "Confirming the fix and closing the ticket.",
  },
  // EAST
  {
    id: "tech_jira",
    x: 1620,
    y: 1500,
    icon: "🎫",
    name: "JIRA / Trello",
    desc: "Moving tickets across the board correctly.",
  },
  {
    id: "tech_logs",
    x: 1720,
    y: 1500,
    icon: "📜",
    name: "Grab Logs",
    desc: "Finding the player.log or output_log.txt file.",
  },
  {
    id: "tech_fps",
    x: 1820,
    y: 1440,
    icon: "📉",
    name: "Performance Checks",
    desc: "Noticing FPS drops in busy areas.",
  },
  {
    id: "tech_specs",
    x: 1820,
    y: 1560,
    icon: "🖥️",
    name: "Hardware Specs",
    desc: "Testing on Low vs High settings.",
  },
  {
    id: "tech_master",
    x: 1950,
    y: 1500,
    type: "keystone",
    icon: "🛠️",
    name: "Toolbox",
    desc: "KEYSTONE: You provide the data needed to fix the bug.",
  },
  {
    id: "tech_console",
    x: 1750,
    y: 1400,
    icon: "⌨️",
    name: "Console Commands",
    desc: "Using cheats/debug commands to skip content.",
  },
  {
    id: "tech_net",
    x: 1850,
    y: 1380,
    icon: "📡",
    name: "Network/Lag",
    desc: "Simulating high ping or packet loss.",
  },
  {
    id: "tech_mobile",
    x: 1850,
    y: 1620,
    icon: "📱",
    name: "Mobile/Input",
    desc: "Touch gestures, controller disconnects, battery.",
  },
  {
    id: "tech_api",
    x: 1680,
    y: 1600,
    icon: "🔌",
    name: "Backend API",
    desc: "Checking if the server is rejecting data.",
  },
  {
    id: "tech_crash",
    x: 2030,
    y: 1500,
    icon: "💥",
    name: "Crash Dumps",
    desc: "Locating the .dmp files after a hard crash.",
  },
  // WEST
  {
    id: "proc_comm",
    x: 1380,
    y: 1500,
    icon: "🗣️",
    name: "Communication",
    desc: "Polite and clear messages to developers.",
  },
  {
    id: "proc_regr",
    x: 1280,
    y: 1500,
    icon: "🔄",
    name: "Regression",
    desc: "Checking if old bugs came back after an update.",
  },
  {
    id: "proc_testplan",
    x: 1180,
    y: 1500,
    icon: "📋",
    name: "Test Cases",
    desc: "Following a checklist without missing items.",
  },
  {
    id: "proc_explore",
    x: 1080,
    y: 1500,
    icon: "🧭",
    name: "Exploratory",
    desc: "Going off-script to find unexpected issues.",
  },
  {
    id: "proc_master",
    x: 950,
    y: 1500,
    type: "keystone",
    icon: "🧠",
    name: "QA Mindset",
    desc: "KEYSTONE: Trust nothing. Test everything.",
  },
  {
    id: "proc_smoke",
    x: 1320,
    y: 1400,
    icon: "💨",
    name: "Smoke Test",
    desc: "Quick check: Does the build even launch?",
  },
  {
    id: "proc_standup",
    x: 1220,
    y: 1400,
    icon: "☕",
    name: "Daily Standup",
    desc: "Giving concise status updates to the team.",
  },
  {
    id: "proc_docs",
    x: 1320,
    y: 1600,
    icon: "📚",
    name: "Documentation",
    desc: "Reading the GDD/Wiki to know how it works.",
  },
  {
    id: "proc_risk",
    x: 1120,
    y: 1580,
    icon: "💣",
    name: "Risk Analysis",
    desc: "Identifying what is most likely to break.",
  },
  {
    id: "proc_lead",
    x: 870,
    y: 1500,
    icon: "👑",
    name: "QA Lead",
    desc: "Mentoring juniors and planning sprints.",
  },
];

export const links = [
  // Center
  { from: "start", to: "gm_mechanics" },
  { from: "start", to: "bug_write" },
  { from: "start", to: "tech_jira" },
  { from: "start", to: "proc_comm" },
  // North
  { from: "gm_mechanics", to: "gm_collision" },
  { from: "gm_mechanics", to: "gm_ui" },
  { from: "gm_mechanics", to: "gm_save" },
  { from: "gm_collision", to: "gm_progression" },
  { from: "gm_ui", to: "gm_progression" },
  { from: "gm_progression", to: "gm_master" },
  { from: "gm_ui", to: "gm_audio" },
  { from: "gm_ui", to: "gm_loc" },
  { from: "gm_mechanics", to: "gm_physics" },
  { from: "gm_progression", to: "gm_tuto" },
  { from: "gm_master", to: "gm_balance" },
  // South
  { from: "bug_write", to: "bug_steps" },
  { from: "bug_steps", to: "bug_media" },
  { from: "bug_steps", to: "bug_sev" },
  { from: "bug_media", to: "bug_master" },
  { from: "bug_sev", to: "bug_master" },
  { from: "bug_write", to: "bug_search" },
  { from: "bug_write", to: "bug_expected" },
  { from: "bug_steps", to: "bug_version" },
  { from: "bug_sev", to: "bug_corner" },
  { from: "bug_master", to: "bug_reopen" },
  // East
  { from: "tech_jira", to: "tech_logs" },
  { from: "tech_logs", to: "tech_fps" },
  { from: "tech_logs", to: "tech_specs" },
  { from: "tech_fps", to: "tech_master" },
  { from: "tech_specs", to: "tech_master" },
  { from: "tech_logs", to: "tech_console" },
  { from: "tech_fps", to: "tech_net" },
  { from: "tech_jira", to: "tech_api" },
  { from: "tech_specs", to: "tech_mobile" },
  { from: "tech_master", to: "tech_crash" },
  // West
  { from: "proc_comm", to: "proc_regr" },
  { from: "proc_regr", to: "proc_testplan" },
  { from: "proc_testplan", to: "proc_explore" },
  { from: "proc_explore", to: "proc_master" },
  { from: "proc_comm", to: "proc_smoke" },
  { from: "proc_smoke", to: "proc_standup" },
  { from: "proc_comm", to: "proc_docs" },
  { from: "proc_testplan", to: "proc_risk" },
  { from: "proc_master", to: "proc_lead" },
];